name: dart_api0v2_network
description: A starting point for Dart libraries or applications.
version: 1.0.7
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dio: ^4.0.6
  path: ^1.8.1
  convert: ^3.0.2
  crypto: ^3.0.2
  http: ^0.13.4
  collection: ^1.16.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
